import type {KitEntry} from './defs';

const FOREST_ECO:KitEntry[]=[
 {id:'forest-dew-leaf',chapter:'forest',category:'interact',name:'露水叶',place:'point',play:'interact',interact:'press',defaults:{s:1},draw:'canvas',mark:'苔'},
 {id:'forest-bounce-mushroom',chapter:'forest',category:'interact',name:'弹跳蘑菇',place:'point',play:'interact',interact:'press',defaults:{s:1},draw:'canvas',mark:'苔'},
 {id:'forest-hollow-fruit',chapter:'forest',category:'interact',name:'空心果',place:'point',play:'interact',interact:'press',defaults:{s:1},draw:'canvas',mark:'苔'},
 {id:'forest-spore-flower',chapter:'forest',category:'interact',name:'孢子花',place:'point',play:'interact',interact:'press',defaults:{s:1},draw:'canvas',mark:'苔'},
 {id:'forest-root-door',chapter:'forest',category:'interact',name:'根须门',place:'point',play:'interact',interact:'press',defaults:{s:1},draw:'canvas',mark:'苔'},
 {id:'forest-firefly-lantern',chapter:'forest',category:'interact',name:'萤火灯笼',place:'point',play:'interact',interact:'press',defaults:{s:1},draw:'canvas',mark:'苔'},
];

export const FOREST_KIT:KitEntry[]=[
 {id:'forest-earth',chapter:'forest',category:'terrain',name:'土地',place:'rect',play:'solid',defaults:{w:400,h:350},draw:'canvas',solidKind:'earth',mark:'苔'},
 {id:'forest-stone',chapter:'forest',category:'terrain',name:'石台',place:'rect',play:'solid',defaults:{w:160,h:80},draw:'canvas',solidKind:'stone',mark:'苔'},
 {id:'forest-root',chapter:'forest',category:'terrain',name:'攀墙树根',place:'rect',play:'solid',interact:'climb',defaults:{w:24,h:200},draw:'canvas',solidKind:'root',mark:'苔'},
 {id:'forest-branch',chapter:'forest',category:'terrain',name:'单向枝',place:'rect',play:'solid',interact:'oneWay',defaults:{w:160,h:16},draw:'canvas',solidKind:'branch',oneWay:true,mark:'苔'},
 {id:'forest-moss',chapter:'forest',category:'terrain',name:'苔台',place:'rect',play:'solid',defaults:{w:200,h:22},draw:'canvas',solidKind:'moss',mark:'苔'},
 {id:'forest-pool-pit',chapter:'forest',category:'terrain',name:'水池坑',place:'rect',play:'solid',defaults:{w:480,h:80},draw:'canvas',solidKind:'pool',mark:'苔'},
 {id:'forest-pool',chapter:'forest',category:'water',name:'镜水',place:'rect',play:'water',defaults:{w:480,h:80},draw:'canvas',mark:'苔'},
 {id:'forest-grass',chapter:'forest',category:'flora',name:'交互草丛',place:'rect',play:'dress',interact:'sway',defaults:{w:120,h:16,s:1},draw:'canvas',mark:'苔'},
 {id:'forest-mushroom',chapter:'forest',category:'flora',name:'蘑菇',place:'point',play:'dress',interact:'sway',defaults:{s:1},draw:'canvas',mark:'苔'},
 {id:'forest-fern',chapter:'forest',category:'flora',name:'蕨',place:'point',play:'dress',interact:'sway',defaults:{s:.8},draw:'canvas',mark:'苔'},
 {id:'forest-flower',chapter:'forest',category:'flora',name:'小花',place:'point',play:'dress',interact:'sway',defaults:{s:1},draw:'canvas',mark:'苔'},
 {id:'dew-forest',chapter:'forest',category:'collect',name:'晨露',place:'point',play:'pickup',pickup:'dew',dewSkin:'forest',defaults:{},draw:'canvas',mark:'苔'},
 {id:'souvenir-mossheart',chapter:'forest',category:'collect',name:'苔心',place:'point',play:'pickup',pickup:'souvenir',souvenirId:'mossheart',defaults:{},draw:'canvas',mark:'苔'},
 {id:'interact-plate',chapter:'forest',category:'interact',name:'踏板',place:'point',play:'interact',interactKind:'plate',interact:'press',defaults:{},draw:'canvas',mark:'苔'},
 {id:'interact-gate',chapter:'forest',category:'interact',name:'石门',place:'rect',play:'interact',interactKind:'gate',defaults:{w:35,h:185},draw:'canvas',mark:'苔'},
 {id:'interact-stake',chapter:'forest',category:'interact',name:'木桩',place:'rect',play:'interact',interactKind:'stake',defaults:{w:28,h:48},draw:'canvas',mark:'苔'},
 {id:'interact-checkpoint',chapter:'forest',category:'interact',name:'检查点',place:'point',play:'interact',interactKind:'checkpoint',defaults:{},draw:'canvas',mark:'苔'},
 {id:'interact-exit',chapter:'forest',category:'interact',name:'终点拱门',place:'rect',play:'interact',interactKind:'exit',defaults:{w:200,h:200},draw:'canvas',mark:'苔'},
 {id:'interact-win-line',chapter:'forest',category:'interact',name:'通关线',place:'point',play:'interact',interactKind:'win-line',defaults:{},draw:'canvas',mark:'苔'},
 {id:'enemy-cap',chapter:'forest',category:'enemy',name:'帽菇仔',place:'point',play:'actor',actorKind:'cap',defaults:{},draw:'canvas',mark:'苔'},
 {id:'enemy-spore',chapter:'forest',category:'enemy',name:'孢子菇',place:'point',play:'actor',actorKind:'spore',defaults:{},draw:'canvas',mark:'苔'},
 {id:'enemy-vine',chapter:'forest',category:'enemy',name:'藤鞭蕨',place:'point',play:'actor',actorKind:'vine',defaults:{},draw:'canvas',mark:'苔'},
 {id:'enemy-pig',chapter:'forest',category:'enemy',name:'野餐猪',place:'point',play:'actor',actorKind:'pig',defaults:{},draw:'canvas',mark:'苔'},
 {id:'enemy-picnic',chapter:'forest',category:'enemy',name:'南宫师姐',place:'point',play:'actor',actorKind:'picnic',defaults:{},draw:'canvas',mark:'苔'},
 {id:'enemy-wolf',chapter:'forest',category:'enemy',name:'霜脊狼',place:'point',play:'actor',actorKind:'wolf',defaults:{},draw:'canvas',mark:'苔'},
 {id:'enemy-boar',chapter:'forest',category:'enemy',name:'杂兵猪',place:'point',play:'actor',actorKind:'boar',defaults:{},draw:'canvas',mark:'苔'},
 {id:'critter-moth',chapter:'forest',category:'critter',name:'蛾',place:'point',play:'dress',defaults:{s:1},draw:'canvas',mark:'苔'},
 {id:'critter-snail',chapter:'forest',category:'critter',name:'蜗牛',place:'point',play:'dress',defaults:{s:1},draw:'canvas',mark:'苔'},
 {id:'critter-beetle',chapter:'forest',category:'critter',name:'叶甲',place:'point',play:'dress',defaults:{s:1},draw:'canvas',mark:'苔'},
 {id:'sign-post',chapter:'forest',category:'sign',name:'路牌',place:'point',play:'sign',defaults:{},draw:'canvas',mark:'苔'},
 {id:'sign-hint',chapter:'forest',category:'sign',name:'提示带',place:'rect',play:'sign',interactKind:'hint',defaults:{w:400,h:200},draw:'canvas',mark:'苔'},
 {id:'sign-area',chapter:'forest',category:'sign',name:'区位名',place:'rect',play:'sign',interactKind:'area',defaults:{w:400,h:400},draw:'canvas',mark:'苔'},
 ...FOREST_ECO,
];
